### ISSUE TITLE
2 or 3 Focal Use Cases would be useful to illustrate layers and optionalities for novice readers

### ISSUE THREAD

**Issue by bumblefudge** [decentralized-identity/secure-data-store#55]
I would be happy to start the ball rolling by editing down Adrian's health report example into something more like the DID-core focal use cases. Any suggestions (or better yet, pull requests!) of other use cases would be much appreciated, as I am no Joe Andreiu.  Off the top of my head, I would particularly welcome focal uses that include:
- all the various topologies mentioned in that section (partic. a CDN and/or multi-cloud example!)
- a regime-change example, to connect to the censorship-resistance functional requirement if that survives
- GDPR examples, such as record-keeping on purpose and/or consent for data retention

https://github.com/agropper/secure-data-store/blob/master/COVID-19_Health_Report_Use_Case.md

Things I personally would find illustrative, but well recognize that these may soon or already be out-of-scope for this group:
- an example of differential privacy and/or "encrypted search," whether MPC-powered or otherwise
- a data union/mydata operator/data trust example

**Comment by bumblefudge** [comment]
Oops forgot link:
https://github.com/agropper/secure-data-store/blob/master/COVID-19_Health_Report_Use_Case.md

**Comment by OR13** [comment]
@agropper I would love to see a healthcare use case as one of the focal points.

**Comment by agropper** [comment]
That's what this is.
https://github.com/agropper/secure-data-store/blob/master/COVID-19_Health_Report_Use_Case.md

But the issue is deeper. I think *all* use-cases need to be complete in the
sense of dealing with realistic business and legal issues. IMHO, too many
of the use-cases are merely nice-to-have requirements that are isolated
from each other. I don't have any problem with being inclusive of every
requirement or nice-to-have but please, try to put these in a realistic
business and legal context.

So, for example, in the Health Report Use Case, I try to address the EFF
concerns around a realistic legislative process.

- Adrian

**Comment by OR13** [comment]
I think another focal use case would be Bank Safe Deposit Boxes... if someone more familiar with banking wants to tackle that, I describe some of it here: https://github.com/decentralized-identity/secure-data-store/issues/41#issuecomment-635511903

**Comment by OR13** [comment]
Here is the usecases doc: https://github.com/decentralized-identity/secure-data-store/blob/master/use_cases.md

**Comment by OR13** [comment]
I'd like to see focal uses cases before requirements.... start general, then get technical later.

**Comment by OR13** [comment]
Lets just try and get a PR in that moves this ball forward.

**Comment by OR13** [comment]
Potentially related: https://github.com/decentralized-identity/secure-data-store/pull/64
