### ISSUE TITLE
Scope question: can a single Secure Data Store manage data for many users?

### ISSUE THREAD

**Issue by jmandel** [decentralized-identity/secure-data-store#73]
After discussion with @agropper, I want to clarify whether the following is in scope (I think it should be, but it's not clear from the discussion up to this point).

1. A national laboratory manages data for millions of patients across the US
2. As a matter of course, the lab leverages SDS to securely store lab results for their patients
3. Each patient is given access to a sub-set (e.g., defined by some combination of types / paths / other attributes) of the data in the SDS, and can in turn delegate access to others (e.g., maybe the patient can delegate by providing a list of DIDs and the capabilities they should have)

The main "wrinkle" in this scenario is that SDS is in no sense a "personal hub"; it's provisioned by (and presumably paid for by) the lab, and narrowly-defined capabilities within the SDS instance are handed out to patients.

(One implication is that to make this delegation work smoothly, the patient should be able to write certain public data to their corner of the SDS -- e.g. to publish their DID so that anyone with a link to relevant data objects can find the patient's DID document and from there discover things like the Service Endpoints where they can go to request access.)

Is this in scope for the SDS project?

**Comment by OR13** [comment]
A single instance should support many clients, where a client is authenticated via a did. Whether those be users or software, is not relevant imo.

In the current EDV model, since the instance cannot see the data or meta data... it actually can't tell anything but how many DIDs are registered with it to store data... and as a use I can register many DIDs... so it has no way of knowing if 1 user is using it, or 100.

**Comment by jmandel** [comment]
Great! 

>  it actually can't tell anything but how many DIDs are registered with it to store data

Or maybe slightly broader: it should know what *kinds* of data a given DID is allowed to manage, or what tags / subpaths data that DID can use for interactions.

Anyway, sounds like this use case is in scope. If nobody disagrees I'll close next week.

**Comment by agropper** [comment]
If I'm understanding @OR13 framing: 

- A Secure Data Store associates a DID with an access scope over data and metadata that the SDS can't see because both data and metadata are assumed to be encrypted.

- The SDS uses the DID to authenticate the scope request by some mechanism related to the contents of the DID document including optionally a service endpoint in the DID document.

- An SDS has a key:value (DID:scope) table where the capability to update this table is itself scoped relative to DIDs already in the table. 

- If the last DID associated with a scope is deleted, 
-- then data and metadata stored under that scope are forever lost in cyberspace and the storage operator might as well delete them to save money, or
-- do they stick around forever for anyone to access

**Comment by OR13** [comment]
Lots to unpack here.

1. An "Encrypted Data Vault" MUST NOT see anything about the kind of data it is storing.

Hubs want to operate on plaintext meta data, and as such are fundamentally less secure than encrypted data vaults from a privacy perspective (they can count meta data)... this has been a continuous point of contention, let's just address it directly.

I'm asserting that an EDV cannot see meta data, and as such, cannot operate on it, outside the concept of indexes, described here: https://identity.foundation/secure-data-store/#indexing

What this means that an EDV operator can't count how many:

- https://schema.org/Offer
- https://example.com/Privacy-Leaking-Schema
- https://example.com/Correlating-Meta-Data-Schema

Or any other attribute of the data it stores.

What it can see is things like this:

```
{
  "edvId": "a783befc-7b8a-4a36-82f7-aebfe0b1b314",
  "indexId": "https://example.com/kms/67891",
  "has": {
    "t2O3VgcSqWzpI6PDQybxiAmXUrepFB48PCoyyUafrZk": ["z19sboJrMo2zhnRvX2kWffxnC"]
  },
  "equals": {
"t2O3VgcSqWzpI6PDQybxiAmXUrepFB48PCoyyUafrZk=znoqUIBRw9G_1ySJc8HGpopmDKdcWaUAOH2M3qni494": [
      "z19sboJrMo2zhnRvX2kWffxnC"
    ]
  }
}
```

Expect the EDV Operator to be as hostile as possible, rely on the client to defend itself as much as possible.

Now for a Hub (A concept at a higher level that can operate on some plaintext meta data), the hub might know how many prescriptions are stored / how many messages about a particular prescription are stored.... its hard to tell, because the hub spec is less developed, and there is not working implementation to pull data model objects from, like I just did for the index.... but that does not mean we can't design around what the hub interface should be, or provide concrete statements about hub functionality... in fact... we need the distinction between hubs and EDVs from an interface perspective to be defined and @csuwildcat is working on that.

Regarding Hubs: Can they support more than 1 user, the answer is yes... can they tell if they are supporting more than one user? maybe... meta data correlation attacks are a thing...

https://en.wikipedia.org/wiki/Traffic_analysis

Hubs by their need to see more data, have more data to use for analysis... lets just assume that a hub operator will that is big enough will have a room where their traffic is collected: https://en.wikipedia.org/wiki/Room_641A

That might be fine IF the user of the system is an opsec genius, and the performance (and data selling) opportunities may make plaintext meta data to irresistible for this working group to avoid... at the hub layer... but its not a thing at the edv layer... and won't be as long as I draw breath :)

To @agropper other question:

deleting of keys is pseudo equivalent to deleting the data... I would expect a vendor to challenge clients to show control of keys, and to automatically delete data which could not be proved to be controlled after some point in time... (in order to save costs).

regarding capabilities (ZCaps), I would rather @dlongley answer the question about where ZCaps are stored.

**Comment by OR13** [comment]
If you don't think plaintext meta data is valuable enough to be stolen or bought, then I invite you to review the basics of surveillance capitalism... and in particular this recent court case: https://www.theverge.com/2020/6/8/21284490/aclu-ladot-mds-lawsuit-scooter-tracking-uber

If the capability exists to see meta data... you can get bet that it will be used for evil.

I might be all for it... I use Google Products, and Windows 10 & Bing Search... I know they make money off tracking me... but I'm not here to build another technology to support surveillance capitalism... I'm here to build a foundational layer that protects data related to DIDs... if people want to disclose their data for faster search results, or more performance, thats their choice... but its not going to be the default.

**Comment by dlongley** [comment]
> regarding capabilities (ZCaps), I would rather @dlongley answer the question about where ZCaps are stored.

That's easy, wherever you want! :P

A likely place to put zcaps would be in a digital wallet -- or other container associated with the party that can invoke them. Note that zcaps are a type of object capability that can only be invoked by someone who can use a key associated with the zcap. This means that there is no security threat created by having a party other than the invoker see a zcap. However, some people may want the information that may be expressed in a zcap (such as where it can be used) to remain confidential.

**Comment by OR13** [comment]
Sorry for hijacking this thread to rant about meta data, I have opened https://github.com/decentralized-identity/secure-data-store/issues/79, please continue the discussion regarding meta data visibility there.

**Comment by jmandel** [comment]
Thanks for the discussion here! I am going to close this as answered in the affirmative :-)
