### ISSUE TITLE
Should metadata be plaintext in Encrypted Data Vaullts?

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/secure-data-store#79]
I suggest no:

https://www.theverge.com/2013/7/17/4517480/nsa-spying-prism-surveillance-cheat-sheet

> In an impassioned plea made by Microsoft on July 16th, the company’s general counsel Brad Smith said: "We believe the US constitution guarantees our freedom to share more information with the public, yet the government is stopping us."

Imagine if it didn't matter what they were forced to share by a NSL... because they couldn't see anything.

**Comment by dhh1128** [comment]
Hyperledger Indy wallets (not mobile apps, but the storage containers underneath them) encrypt nearly all metadata by default; it is possible to erode this position slightly, but not *in toto*. See https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0050-wallets#types-of-sovereign-data and also the "Tags and Queries" section just above that.

The reason we did this is that these containers are specialized to store data on ]the more sensitive side of the sensitivity spectrum](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0050-wallets#types-of-sovereign-data). They're not for storing your cat photos.

Because EDVs aspire to store all data, the problem space is broader, and that creates more tensions. Having metadata be plaintext increase the options and decreases the complexity (and probably size and performance) of your indexing strategy, but it also lets configuration shoot the user in the foot when it's done unwisely. If it were me, I'd probably pick secure by default and side with Orie that the answer should be "no."

**Comment by OR13** [comment]
Closing we have reached consensus on this issue.
